name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies & Run Tests in Virtual Environment
        run: |
          cd backend  # Ensure we're in the right directory
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install fastapi uvicorn pytest  # Ensure required packages are installed
          pip list  # Debugging: Check installed packages
          python -c "import fastapi; print('FastAPI Installed Successfully')"  # Debugging step

          # Ensure pytest finds the correct modules
          export PYTHONPATH=$PWD  # Set Python path to the backend directory
          pytest tests/  # Run tests inside the virtual environment

  docker:
    name: Build & Push Docker Image
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Image Tag
        id: docker_meta
        run: echo "IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_TAG }} backend/

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ env.IMAGE_TAG }}
